### ISSUE TITLE
Inconsistent Team Representation and Diagonal Discrepancies for schedule output

### ISSUE THREAD

**Issue by xzc21** [AndersonHsieh0330/serve_tournament_scripts#1]
# Description:
In your `example_output.txt`, there's 14 teams but only 13 teams for the columns. Not only for example outputs, but when running the script also.

Additionally, the matrix should be perfectly symmetrical along the diagonal, but it currently contains discrepancies.

# Example:
* Cell (T4,T8) should be the same value as cell (T8,T4) but it's not
* See the attached image for reference:

![image](https://github.com/AndersonHsieh0330/serve_tournament_scripts/assets/70451028/ce3f1447-f1f4-4945-81ba-d1b336c9dd59)

# Steps to Reproduce:

    Generate the output.txt using the current script.
    Observe the team count and matrix symmetry.

# Expected Behavior:

    The team count in rows and columns should match.
    The values should be symmetrical along the diagonal.

**Comment by AndersonHsieh0330** [comment]
The matrix is symmetrical, the row team index starts with 0 and column team index starts with 1. I'll fix that
I'll also fix the missing rows and columns on the output matrix 
EDIT: no rows/columns missing on output

**Comment by AndersonHsieh0330** [comment]
fixed in 9ddd282d9f25642937fca3a14d8396f6a7bc3906
